In [ ]:
from keras.utils import text_dataset_from_directory
from keras.preprocessing import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[934, 9883, 4728, 9333],
 [934, 9883, 4728, 9383],
 [934, 1152, 4728, 2450],
 [1421, 1882, 833, 6767, 9279],
 [1421, 1882, 833, 6767, 7172],
 [9505, 934, 3159, 4728, 687],
 [1145, 2904, 6633, 6767]]

In [7]:
## word Embedding Representation

from keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from keras.utils import pad_sequences
from keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  934 9883 4728 9333]
 [   0    0    0    0  934 9883 4728 9383]
 [   0    0    0    0  934 1152 4728 2450]
 [   0    0    0 1421 1882  833 6767 9279]
 [   0    0    0 1421 1882  833 6767 7172]
 [   0    0    0 9505  934 3159 4728  687]
 [   0    0    0    0 1145 2904 6633 6767]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\prana\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step   


array([[[-1.1129759e-02, -3.9520513e-02, -2.1112656e-02, -1.7526865e-02,
         -2.7563645e-02, -3.2880448e-02, -4.1620873e-02, -8.3907619e-03,
          4.9312960e-02,  1.5882280e-02],
        [-1.1129759e-02, -3.9520513e-02, -2.1112656e-02, -1.7526865e-02,
         -2.7563645e-02, -3.2880448e-02, -4.1620873e-02, -8.3907619e-03,
          4.9312960e-02,  1.5882280e-02],
        [-1.1129759e-02, -3.9520513e-02, -2.1112656e-02, -1.7526865e-02,
         -2.7563645e-02, -3.2880448e-02, -4.1620873e-02, -8.3907619e-03,
          4.9312960e-02,  1.5882280e-02],
        [-1.1129759e-02, -3.9520513e-02, -2.1112656e-02, -1.7526865e-02,
         -2.7563645e-02, -3.2880448e-02, -4.1620873e-02, -8.3907619e-03,
          4.9312960e-02,  1.5882280e-02],
        [-4.9590159e-02,  1.3595257e-02,  3.2962803e-02,  3.4162629e-02,
         -2.6312137e-02,  2.2473726e-02, -1.4545787e-02, -9.8014474e-03,
         -2.2964740e-02,  3.5129897e-03],
        [ 2.5933232e-02,  9.6581690e-03,  6.1540380e-03,  3.

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0,  934, 9883, 4728, 9333])

In [15]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step


array([[[-1.1129759e-02, -3.9520513e-02, -2.1112656e-02, -1.7526865e-02,
         -2.7563645e-02, -3.2880448e-02, -4.1620873e-02, -8.3907619e-03,
          4.9312960e-02,  1.5882280e-02],
        [-1.1129759e-02, -3.9520513e-02, -2.1112656e-02, -1.7526865e-02,
         -2.7563645e-02, -3.2880448e-02, -4.1620873e-02, -8.3907619e-03,
          4.9312960e-02,  1.5882280e-02],
        [-1.1129759e-02, -3.9520513e-02, -2.1112656e-02, -1.7526865e-02,
         -2.7563645e-02, -3.2880448e-02, -4.1620873e-02, -8.3907619e-03,
          4.9312960e-02,  1.5882280e-02],
        [-1.1129759e-02, -3.9520513e-02, -2.1112656e-02, -1.7526865e-02,
         -2.7563645e-02, -3.2880448e-02, -4.1620873e-02, -8.3907619e-03,
          4.9312960e-02,  1.5882280e-02],
        [-4.9590159e-02,  1.3595257e-02,  3.2962803e-02,  3.4162629e-02,
         -2.6312137e-02,  2.2473726e-02, -1.4545787e-02, -9.8014474e-03,
         -2.2964740e-02,  3.5129897e-03],
        [ 2.5933232e-02,  9.6581690e-03,  6.1540380e-03,  3.